const buildCommonsUrl = (script, slug) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${script}_${slug}_stroke_order_animation.gif`;

const HIRAGANA_ANIMATIONS = {
  a: buildCommonsUrl('Hiragana', 'a'),
  i: buildCommonsUrl('Hiragana', 'i'),
  u: buildCommonsUrl('Hiragana', 'u'),
  e: buildCommonsUrl('Hiragana', 'e'),
  o: buildCommonsUrl('Hiragana', 'o'),
  ka: buildCommonsUrl('Hiragana', 'ka'),
  ki: buildCommonsUrl('Hiragana', 'ki'),
  ku: buildCommonsUrl('Hiragana', 'ku'),
  ke: buildCommonsUrl('Hiragana', 'ke'),
  ko: buildCommonsUrl('Hiragana', 'ko'),
  sa: buildCommonsUrl('Hiragana', 'sa'),
  shi: buildCommonsUrl('Hiragana', 'shi'),
  su: buildCommonsUrl('Hiragana', 'su'),
  se: buildCommonsUrl('Hiragana', 'se'),
  so: buildCommonsUrl('Hiragana', 'so'),
  ta: buildCommonsUrl('Hiragana', 'ta'),
  chi: buildCommonsUrl('Hiragana', 'chi'),
  tsu: buildCommonsUrl('Hiragana', 'tsu'),
  te: buildCommonsUrl('Hiragana', 'te'),
  to: buildCommonsUrl('Hiragana', 'to'),
  na: buildCommonsUrl('Hiragana', 'na'),
  ni: buildCommonsUrl('Hiragana', 'ni'),
  nu: buildCommonsUrl('Hiragana', 'nu'),
  ne: buildCommonsUrl('Hiragana', 'ne'),
  no: buildCommonsUrl('Hiragana', 'no'),
  ha: buildCommonsUrl('Hiragana', 'ha'),
  hi: buildCommonsUrl('Hiragana', 'hi'),
  fu: buildCommonsUrl('Hiragana', 'fu'),
  he: buildCommonsUrl('Hiragana', 'he'),
  ho: buildCommonsUrl('Hiragana', 'ho'),
  ma: buildCommonsUrl('Hiragana', 'ma'),
  mi: buildCommonsUrl('Hiragana', 'mi'),
  mu: buildCommonsUrl('Hiragana', 'mu'),
  me: buildCommonsUrl('Hiragana', 'me'),
  mo: buildCommonsUrl('Hiragana', 'mo'),
  ya: buildCommonsUrl('Hiragana', 'ya'),
  yu: buildCommonsUrl('Hiragana', 'yu'),
  yo: buildCommonsUrl('Hiragana', 'yo'),
  ra: buildCommonsUrl('Hiragana', 'ra'),
  ri: buildCommonsUrl('Hiragana', 'ri'),
  ru: buildCommonsUrl('Hiragana', 'ru'),
  re: buildCommonsUrl('Hiragana', 're'),
  ro: buildCommonsUrl('Hiragana', 'ro'),
  wa: buildCommonsUrl('Hiragana', 'wa'),
  wo: buildCommonsUrl('Hiragana', 'wo'),
  n: buildCommonsUrl('Hiragana', 'n'),
  ga: buildCommonsUrl('Hiragana', 'ga'),
  gi: buildCommonsUrl('Hiragana', 'gi'),
  gu: buildCommonsUrl('Hiragana', 'gu'),
  ge: buildCommonsUrl('Hiragana', 'ge'),
  go: buildCommonsUrl('Hiragana', 'go'),
  za: buildCommonsUrl('Hiragana', 'za'),
  ji: buildCommonsUrl('Hiragana', 'ji'),
  zu: buildCommonsUrl('Hiragana', 'zu'),
  ze: buildCommonsUrl('Hiragana', 'ze'),
  zo: buildCommonsUrl('Hiragana', 'zo'),
  da: buildCommonsUrl('Hiragana', 'da'),
  di: buildCommonsUrl('Hiragana', 'di'),
  du: buildCommonsUrl('Hiragana', 'du'),
  de: buildCommonsUrl('Hiragana', 'de'),
  do: buildCommonsUrl('Hiragana', 'do'),
  ba: buildCommonsUrl('Hiragana', 'ba'),
  bi: buildCommonsUrl('Hiragana', 'bi'),
  bu: buildCommonsUrl('Hiragana', 'bu'),
  be: buildCommonsUrl('Hiragana', 'be'),
  bo: buildCommonsUrl('Hiragana', 'bo'),
  pa: buildCommonsUrl('Hiragana', 'pa'),
  pi: buildCommonsUrl('Hiragana', 'pi'),
  pu: buildCommonsUrl('Hiragana', 'pu'),
  pe: buildCommonsUrl('Hiragana', 'pe'),
  po: buildCommonsUrl('Hiragana', 'po'),
  kya: buildCommonsUrl('Hiragana', 'kya'),
  kyu: buildCommonsUrl('Hiragana', 'kyu'),
  kyo: buildCommonsUrl('Hiragana', 'kyo'),
  sha: buildCommonsUrl('Hiragana', 'sha'),
  shu: buildCommonsUrl('Hiragana', 'shu'),
  sho: buildCommonsUrl('Hiragana', 'sho'),
  cha: buildCommonsUrl('Hiragana', 'cha'),
  chu: buildCommonsUrl('Hiragana', 'chu'),
  cho: buildCommonsUrl('Hiragana', 'cho'),
  nya: buildCommonsUrl('Hiragana', 'nya'),
  nyu: buildCommonsUrl('Hiragana', 'nyu'),
  nyo: buildCommonsUrl('Hiragana', 'nyo'),
  hya: buildCommonsUrl('Hiragana', 'hya'),
  hyu: buildCommonsUrl('Hiragana', 'hyu'),
  hyo: buildCommonsUrl('Hiragana', 'hyo'),
  mya: buildCommonsUrl('Hiragana', 'mya'),
  myu: buildCommonsUrl('Hiragana', 'myu'),
  myo: buildCommonsUrl('Hiragana', 'myo'),
  rya: buildCommonsUrl('Hiragana', 'rya'),
  ryu: buildCommonsUrl('Hiragana', 'ryu'),
  ryo: buildCommonsUrl('Hiragana', 'ryo'),
  gya: buildCommonsUrl('Hiragana', 'gya'),
  gyu: buildCommonsUrl('Hiragana', 'gyu'),
  gyo: buildCommonsUrl('Hiragana', 'gyo'),
  ja: buildCommonsUrl('Hiragana', 'ja'),
  ju: buildCommonsUrl('Hiragana', 'ju'),
  jo: buildCommonsUrl('Hiragana', 'jo'),
  bya: buildCommonsUrl('Hiragana', 'bya'),
  byu: buildCommonsUrl('Hiragana', 'byu'),
  byo: buildCommonsUrl('Hiragana', 'byo'),
  pya: buildCommonsUrl('Hiragana', 'pya'),
  pyu: buildCommonsUrl('Hiragana', 'pyu'),
  pyo: buildCommonsUrl('Hiragana', 'pyo')
};

const KATAKANA_ANIMATIONS = {
  a: buildCommonsUrl('Katakana', 'a'),
  i: buildCommonsUrl('Katakana', 'i'),
  u: buildCommonsUrl('Katakana', 'u'),
  e: buildCommonsUrl('Katakana', 'e'),
  o: buildCommonsUrl('Katakana', 'o'),
  ka: buildCommonsUrl('Katakana', 'ka'),
  ki: buildCommonsUrl('Katakana', 'ki'),
  ku: buildCommonsUrl('Katakana', 'ku'),
  ke: buildCommonsUrl('Katakana', 'ke'),
  ko: buildCommonsUrl('Katakana', 'ko'),
  sa: buildCommonsUrl('Katakana', 'sa'),
  shi: buildCommonsUrl('Katakana', 'shi'),
  su: buildCommonsUrl('Katakana', 'su'),
  se: buildCommonsUrl('Katakana', 'se'),
  so: buildCommonsUrl('Katakana', 'so'),
  ta: buildCommonsUrl('Katakana', 'ta'),
  chi: buildCommonsUrl('Katakana', 'chi'),
  tsu: buildCommonsUrl('Katakana', 'tsu'),
  te: buildCommonsUrl('Katakana', 'te'),
  to: buildCommonsUrl('Katakana', 'to'),
  na: buildCommonsUrl('Katakana', 'na'),
  ni: buildCommonsUrl('Katakana', 'ni'),
  nu: buildCommonsUrl('Katakana', 'nu'),
  ne: buildCommonsUrl('Katakana', 'ne'),
  no: buildCommonsUrl('Katakana', 'no'),
  ha: buildCommonsUrl('Katakana', 'ha'),
  hi: buildCommonsUrl('Katakana', 'hi'),
  fu: buildCommonsUrl('Katakana', 'fu'),
  he: buildCommonsUrl('Katakana', 'he'),
  ho: buildCommonsUrl('Katakana', 'ho'),
  ma: buildCommonsUrl('Katakana', 'ma'),
  mi: buildCommonsUrl('Katakana', 'mi'),
  mu: buildCommonsUrl('Katakana', 'mu'),
  me: buildCommonsUrl('Katakana', 'me'),
  mo: buildCommonsUrl('Katakana', 'mo'),
  ya: buildCommonsUrl('Katakana', 'ya'),
  yu: buildCommonsUrl('Katakana', 'yu'),
  yo: buildCommonsUrl('Katakana', 'yo'),
  ra: buildCommonsUrl('Katakana', 'ra'),
  ri: buildCommonsUrl('Katakana', 'ri'),
  ru: buildCommonsUrl('Katakana', 'ru'),
  re: buildCommonsUrl('Katakana', 're'),
  ro: buildCommonsUrl('Katakana', 'ro'),
  wa: buildCommonsUrl('Katakana', 'wa'),
  wo: buildCommonsUrl('Katakana', 'wo'),
  n: buildCommonsUrl('Katakana', 'n'),
  ga: buildCommonsUrl('Katakana', 'ga'),
  gi: buildCommonsUrl('Katakana', 'gi'),
  gu: buildCommonsUrl('Katakana', 'gu'),
  ge: buildCommonsUrl('Katakana', 'ge'),
  go: buildCommonsUrl('Katakana', 'go'),
  za: buildCommonsUrl('Katakana', 'za'),
  ji: buildCommonsUrl('Katakana', 'ji'),
  zu: buildCommonsUrl('Katakana', 'zu'),
  ze: buildCommonsUrl('Katakana', 'ze'),
  zo: buildCommonsUrl('Katakana', 'zo'),
  da: buildCommonsUrl('Katakana', 'da'),
  di: buildCommonsUrl('Katakana', 'di'),
  du: buildCommonsUrl('Katakana', 'du'),
  de: buildCommonsUrl('Katakana', 'de'),
  do: buildCommonsUrl('Katakana', 'do'),
  ba: buildCommonsUrl('Katakana', 'ba'),
  bi: buildCommonsUrl('Katakana', 'bi'),
  bu: buildCommonsUrl('Katakana', 'bu'),
  be: buildCommonsUrl('Katakana', 'be'),
  bo: buildCommonsUrl('Katakana', 'bo'),
  pa: buildCommonsUrl('Katakana', 'pa'),
  pi: buildCommonsUrl('Katakana', 'pi'),
  pu: buildCommonsUrl('Katakana', 'pu'),
  pe: buildCommonsUrl('Katakana', 'pe'),
  po: buildCommonsUrl('Katakana', 'po'),
  kya: buildCommonsUrl('Katakana', 'kya'),
  kyu: buildCommonsUrl('Katakana', 'kyu'),
  kyo: buildCommonsUrl('Katakana', 'kyo'),
  sha: buildCommonsUrl('Katakana', 'sha'),
  shu: buildCommonsUrl('Katakana', 'shu'),
  sho: buildCommonsUrl('Katakana', 'sho'),
  cha: buildCommonsUrl('Katakana', 'cha'),
  chu: buildCommonsUrl('Katakana', 'chu'),
  cho: buildCommonsUrl('Katakana', 'cho'),
  nya: buildCommonsUrl('Katakana', 'nya'),
  nyu: buildCommonsUrl('Katakana', 'nyu'),
  nyo: buildCommonsUrl('Katakana', 'nyo'),
  hya: buildCommonsUrl('Katakana', 'hya'),
  hyu: buildCommonsUrl('Katakana', 'hyu'),
  hyo: buildCommonsUrl('Katakana', 'hyo'),
  mya: buildCommonsUrl('Katakana', 'mya'),
  myu: buildCommonsUrl('Katakana', 'myu'),
  myo: buildCommonsUrl('Katakana', 'myo'),
  rya: buildCommonsUrl('Katakana', 'rya'),
  ryu: buildCommonsUrl('Katakana', 'ryu'),
  ryo: buildCommonsUrl('Katakana', 'ryo'),
  gya: buildCommonsUrl('Katakana', 'gya'),
  gyu: buildCommonsUrl('Katakana', 'gyu'),
  gyo: buildCommonsUrl('Katakana', 'gyo'),
  ja: buildCommonsUrl('Katakana', 'ja'),
  ju: buildCommonsUrl('Katakana', 'ju'),
  jo: buildCommonsUrl('Katakana', 'jo'),
  bya: buildCommonsUrl('Katakana', 'bya'),
  byu: buildCommonsUrl('Katakana', 'byu'),
  byo: buildCommonsUrl('Katakana', 'byo'),
  pya: buildCommonsUrl('Katakana', 'pya'),
  pyu: buildCommonsUrl('Katakana', 'pyu'),
  pyo: buildCommonsUrl('Katakana', 'pyo')
};

const animationMap = {
  hiragana: HIRAGANA_ANIMATIONS,
  katakana: KATAKANA_ANIMATIONS
};

export const getAnimationUrl = (type, romaji) => {
  if (!type || !romaji) {
    return null;
  }
  return animationMap[type]?.[romaji.toLowerCase()] || null;
};

export const getAvailableAnimations = (type) => {
  if (!type || !animationMap[type]) {
    return {};
  }
  return animationMap[type];
};
